### PR TITLE
[RS][DDCE-1051] Updating language toggle placement for accessibility.

### PR DESCRIPTION
**Pull request by RafSobol**
# DDCE-1051

## Accessibility improvement

The language toggle placement within the content div was found to be bad for screen reader users, due to the skip link moving the user to it first, rather than to the main content. In order to resolve this issue without implementing a custom template, the language toggle was moved to the bottom of the service info block, above the main "content" div.

## PR Suggestions
- Have you looked at the JIRA story to make sure all Acceptance Criteria has been met?
- Have you done a visual check of the changes?
- Is there any still commented or unused code? Lingering printlns?
- Have things been implemented in a complicated way?
- Are the test still over the coverage threshold?
- Does the compiler throw a lot of warnings? 
- Have methods and tests been named clearly?
- Were there any changes in the config? Do changes need to be made in app-config-???

## Checklist PR Raiser
 - [x]  I've made every effort to commit high quality, clean code and I have executed relevant static analyses to be sure
 - [ ]  I've included appropriate tests with any code I've added (Unit, Integration, Acceptance etc.)
 - [x]  I've executed the acceptance test pack locally to ensure there are no functional regressions (Performance tests where relevant)
 - [x]  I've squashed my commits - including the JIRA issue number in the commit message
 - [x]  I've run a dependency check to ensure all dependencies are up to date

## Checklist PR Reviewer
 - [ ]  I've made every effort to commit high quality, clean code and I have executed relevant static analyses to be sure
 - [ ]  I've included appropriate tests with any code I've added (Unit, Integration, Acceptance etc.)
 - [x]  I've executed the acceptance test pack locally to ensure there are no functional regressions (Performance tests where relevant)
 - [ ]  I've squashed my commits - including the JIRA issue number in the commit message
 - [x]  I've run a dependency check to ensure all dependencies are up to date

### CODE REVIEW

**Comment by DannyPennington97** [comment]
So after battling with the mac voice over for a bit it seems like the "skip to main content" button now skips you to the back button if one is present on the page instead of the welsh toggle. The back button is only on /enter-company-details and /check-your-answers and it looks like it's just been placed on those two pages at the start of the main content and not put in using the wrapper

**Comment by RafSobol** [comment]
good point - on it

**Comment by RafSobol** [comment]
fixed & pushed up

**Comment by DannyPennington97** [comment]
Nice one, looks good to me

**Review by DannyPennington97 — APPROVED** [review]

**Pull request merged**
